# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12cef638ec0c369730c3c21c3372f0c9"
name = "ecom-kit"
handle = "ecom-kit-2"
application_url = "https://feature-screenshots-combined-rope.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://feature-screenshots-combined-rope.trycloudflare.com/auth/callback",
  "https://feature-screenshots-combined-rope.trycloudflare.com/auth/shopify/callback",
  "https://feature-screenshots-combined-rope.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
